version: '3.4'

services:
  sqlDB:
    container_name: WuhanDB
    networks:
        - myNet1
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:                
        - 3307:3306
    volumes:
        - BackUpSql:/var/opt/mssql
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=q1W@e3r4t5
  seekanddestroy:
        container_name: WuhanSaD
        networks: 
            - myNet1
        image: ${DOCKER_REGISTRY-}seekanddestroy
        ports:                
                - 7777:443
        environment:
            - ConnectionDB=Server=WuhanDB; Database=SaDDB; User Id=sa; Password=q1W@e3r4t5; Trust Server Certificate=True;


        build:
          context: .
          dockerfile: SeekAndDestroy/Dockerfile

    
networks:
  myNet1:
volumes:
    BackUpSql:


  
